"""add category

Revision ID: 7d53762ededa
Revises:
Create Date: 2026-01-20 13:11:23.325058

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7d53762ededa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
