"""add category second try

Revision ID: e93dfe39336a
Revises: 7d53762ededa
Create Date: 2026-01-20 13:36:56.564319

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e93dfe39336a"
down_revision: Union[str, Sequence[str], None] = "7d53762ededa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
